<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 *
 * @var $this \Engine\App\Documentation\View\View
 */
$this->extend('Documentation::skeleton.phtml');
?>
<h1>Open Source</h1>

Thank's to the all people contributing open source software.<br/>
This is a list of projects which are used or inspired the <code>engine</code> framework.<br><br>

Especially<br/>
<ul>
    <li>Altorouter <a href="https://github.com/dannyvankooten/AltoRouter" target="_blank">https://github.com/dannyvankooten/AltoRouter</a></li>
    <li>Spot2 <a href="https://github.com/spotorm/spot2" target="_blank">https://github.com/spotorm/spot2</a></li>
    <li>PHPUnit <a href="https://github.com/sebastianbergmann/phpunit" target="_blank">https://github.com/sebastianbergmann/phpunit</a></li>
    <li>Fontawesome <a href="https://github.com/FortAwesome/Font-Awesome" target="_blank">https://github.com/FortAwesome/Font-Awesome</a></li>
    <li>Spyc <a href="https://github.com/mustangostang/spyc" target="_blank">https://github.com/mustangostang/spyc</a></li>
    <li>SB Admin 2 Bootstrap Theme <a href="https://github.com/BlackrockDigital/startbootstrap-sb-admin-2" target="_blank">https://github.com/BlackrockDigital/startbootstrap-sb-admin-2</a></li>
</ul>
