<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 *
 * @var $this \Engine\App\Documentation\View\View
 */
$this->extend('Documentation::skeleton.phtml');
?>
<h1>Overview</h1>

This is the documentation of the <a href="https://github.com/mmethner/engine" target="_blank">engine php framework</a>.<br/>
<code>Engine</code> aims to be a lightweight and easy to learn  piece of software.<br/><br/>

When you see this page, you already use <code>engine</code>, since the documentation is powered by the <code>engine core</code>.

