<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 *
 * @var $this \Engine\App\Documentation\View\View
 */
?>
<!DOCTYPE html>
<html>
<head>
    <title>Engine\App Documentation</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="robots" content="index, follow, all"/>
    <meta name="Author" content="Mathias Methner"/>
    <meta name="Keywords" content="php, framework, mvc, engine, engine-app"/>

    <?=$this->favicon('documentation::favicon.png');?>

    <?=$this->stylesheet('documentation::sb-admin-2/bootstrap.min.css');?>
    <?=$this->stylesheet('documentation::sb-admin-2/metisMenu.min.css');?>
    <?=$this->stylesheet('documentation::sb-admin-2/font-awesome/css/font-awesome.min.css');?>
    <?=$this->stylesheet('documentation::sb-admin-2/sb-admin-2.css');?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?=$this->javascript('documentation::sb-admin-2/jquery.min.js');?>

</head>
<body>
<div id="wrapper">

    <nav class="navbar navbar-default navbar-static-top"
         role="navigation"
         style="margin-bottom: 0; width: 100%;">

        <? $this->renderSnippet('Documentation::navigation/top.phtml'); ?>
        <? $this->renderSnippet('Documentation::navigation/left.phtml'); ?>

    </nav>

    <div id="page-wrapper">
        <div class="container-fluid">
            <?=$this->content();?>
        </div>
    </div>

</div>

<?=$this->javascript('documentation::sb-admin-2/bootstrap.min.js');?>
<?=$this->javascript('documentation::sb-admin-2/metisMenu.min.js');?>
<?=$this->javascript('documentation::sb-admin-2/sb-admin-2.js');?>

</body>
</html>