<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 *
 * @var $this \Engine\App\Documentation\View\View
 */
?>
<!DOCTYPE html>
<html>
<head>
    <title>Engine\App Documentation</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="robots" content="index, follow, all"/>
    <meta name="Author" content="Mathias Methner"/>
    <meta name="Keywords"
          content="php, framework, mvc, engine, engine-app"/>
    <?=$this->favicon('documentation::favicon.png');?>
    <?=$this->stylesheet('documentation::stylesheet.css');?>
</head>
<body>
<?=$this->content();?>
</body>
</html>