routes:
  default: ['', 'Documentation::Controller', overviewAction]
  root: ['/', 'Documentation::Controller', overviewAction]
  overview: ['/overview', 'Documentation::Controller', overviewAction]
  module: ['/module', 'Documentation::Controller', moduleAction]
  oss: ['/oss', 'Documentation::Controller', ossAction]
