<?php
/*
 * This file is part of the Engine framework.
 * (c) Mathias Methner <mathiasmethner@gmail.com>
 * Please view the LICENSE file
 *
 * @var $this \Engine\App\Documentation\View\View
 */
?>
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-collapse">
        <span class="sr-only"><?=\Trans::late('Toggle navigation');?></span> <span
                class="icon-bar"></span> <span class="icon-bar"></span> <span
                class="icon-bar"></span>
    </button>

    <a class="navbar-brand"
       href="<?=$this->route('Documentation::Controller::overview');?>">
        <?=\Trans::late('engine demo app');?></a>

</div>

<div class="nav navbar-top-links navbar-right" style="margin: 15px;">
    Contact <a href="mailto:mathiasmethner@gmail.com?subject=Engine App"><i class="fa fa-envelop"></i> Mathias Methner</a>

    or <a href="https://github.com/mmethner" target="_blank"><i class="fa fa-github"></i> mmethner</a>
</div>
